version: '3.4'
services:
  pigeon:
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=pigeon;username=postgres;password=aaaaaaaaa"
      ASPNETCORE_ENVIRONMENT: Development
    networks:
          - shared

networks:
  shared: 
    external:
      name: shared